language: go
go:
- 1.5
- 1.6
- 1.7
- 1.8
install:
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
- go get github.com/satori/go.uuid
- go get gopkg.in/check.v1
script:
- cd sts
- travis_wait 30 go test -v -covermode=count -coverprofile=coverage.out -timeout=30m
- $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci
env:
  global:
  - secure: Wxp4SIJrGetnf1G1qvg5LLWPc2JDkqf2pQfXV+nZr76lyhkrerEDBcslzuAxYQMe3YCEgio5Ayk9owZjyIHjoO6Kef77cBL3QsXq51qYJT5GIhdaSGk5p7BCwy9lYaV90ljebEKSnpRO9zElh6grc3THlqUe4VScPmoMVeUP6RGRp15F+L8ecy+kEEbtMpks25htOQttqGZqvIn6uM64gdjFi/ZNZi2PN0FH0MFP2+440PvbAJpUl8Ev+tkaohiuWSv4gg1jxUO7QA0g+tNaCfstUadxxnDvAItTnFW3RzZU0Kpj3xtjf8TzaI2Q9mTiZ/GcN3RsUSF4OZefcc3M5T4C9iD5kYHP1WXvGC6Z8HOW4aHSZluD8g+l+I5kvCr1sQ/Ae/1k/dX1NlSZQr9UEaq2tsx/lNhI4y30Hp3OSC9wzeswcZSiA4P9G8LMoD2p3y18V+XCis8Nt8Eg7kjc0TqeMu2Ltx04ZtNB28faEPBNfrdSEFsPt3+H5fgRUDkfK7n7IW54i7AUnQx/UG+ewL+IoQLkDeXUxlytwvDYyZAKMf5ZSV15uiNHz/Kq6++TPcDpeO3SSoFAWlUj8xeQC2R6a9n4o03T/J0d/hTS7A0p7VRW0b/VIiZ7QPeo6JIosMUDkjwpon0otTio2MtH83tdVEKHDjMy7lkKJgSIQwU=
  - secure: a5Rkh6GjYQFILfnhVfX0ubdngpuCD2e0rXicD1+wzOBw46PoyWqzJshAFOJHS2C8IWfxe42KWD1uckzt1mxw2eETOM7r5Pp3DAeYchTWziHL3EEL1WG62wMdvxQRGSBz20N08DDfyK65g/2a+DQv8x8ZayZivg7wZc22fPOFEp8qDBetKs+LaEnAnxLBnuwhEKbGrXJ2kFBhKBLeAq7De759SFKBca8K5SVkRfgwqjnh/3i+oPBUketwztiXee5m36vFVjWoMxEF7t2kQO8I18Eew2syD/nOm6BzH06PyStsadoYcK381h7HUVUYNqMQk6l4mDFXNbNIrap8/spuOeVDsYI+O68Zh1mfnJfJDxFuiFzXVfvp+YxeT1aY2Yk4gstCWPUBUxHdLNuZrdMUO18boHXqQDiRKXHQl26pq7WTddNC/l3MTpufBN2EOQKqrUvKSb0YaEwit9Wq1IuIZsC0+UnqyhMTIhZIuD3HY/Mdm9FmwF0v8/a40I+aRIiqc6FSG20Warn2pKFNULRTGwgTn2JXdtsqNov+jD4gHLYLu1AHssHDZD8IcFXxylXF4VvF2Y030i22rUfP10kmfBqphFyGRs+vB3E01S02mlXnRXzRf95RzqXEzK1ezyb6vfZciZ966HPhybbbtoNBamvm/rWVHg5xNod5oeu1OI4=
  - secure: MK7zDaxpLwT+ItLDPMzc5SQOmtVrWAsc+cbCtPaYlFdXb8zKc4U3W8oIDNHajvwGPW+jB3vN0xarfiC7H9+q+I/JEViIgHGXwOt/P75tdIf7IkUHmOeEEbOHBsuV8roFOzDu4XkrYNkJG5qWxOvLtG+f4jW3bCZGL5FxdS2QIn5qBqy1v85QBrV1FKNKw+DOvHieGRul7MlGHAPCq5WWx/xyoxD1y1mDdTlFPduetcjOstsHd110Kr9SFUVu7jmvTU13S3mdkRGGN1FX3tWHiBLwhyIOOI0otuLfzq/9gsLtEoWH32/IKtMwH+Uu45gFn2ddP1cL4J42JxQcEJnE9e23E/XDuwYjV1NJBa+YgpOwUM98yBi+9AQ4+CQ+gLr+TQ6hbPyf9DqGSH0hXbY76+mnGZYSd33iVEjUdJe+82xnK/BXsqgAXXq2cIgNIjebUcgyiMHIt6s5ECzHRLcE4Hsj9lSRpEhv7fjvKq80mWsOoQa5tSoIEQx1pP/R8cyQCnX7eJBs/kbePg1Nwi3pC7WsCFxotCdxKajM7jXtdYBdHf2Fbuna3prIJEwP8lLJlBuQfwijq9DROvUovJN0wPPXuPOYX8O1LNY4wPsgX38PWzUCu2LQ6u0ztAWPio/7ZnxvbPysVMrMI2ENAadUotlDuGaSA7UhT0CAmbdexjo=
